# Generated by Django 6.0.3 on 2026-07-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
